### ISSUE TITLE
Handle of Multiple Attributes

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA-LwM2M-Public-Review#5]
TS, section 5.3.4 Table 9 Write Attribute parameters.
The table doesn't indicate how to handle multiple attributes, e.g. `AND`, `OR`.

Clarification is needed to the following use case.

**Comment by mkovatsc** [comment]
In [draft-ietf-core-interfaces-02](https://tools.ietf.org/html/draft-ietf-core-interfaces-02) st, lt, and gt have lower priority than the period parameters (pmin, pmax). Notifications are sent with pmax even when the value is above lt or the change smaller than st. This way, observers can ensure if they are still on the list of observers. This might not be necessary for LWM2M, since there is the registration update to inform about liveliness and the TS can forbid overwriting observer slots that are in use. However, we would maximize interoperability and have a better basis for a future device-to-device mode when sticking to draft-ietf-core-interfaces.

There is no information on the conjunction of lt and gt, though. Usually a query implies the AND conjunction (e.g., for the Link Format discovery filtering). This would only allow Notifications within an interval. Hence, LWM2M should define (lt OR gt) if (lt < gt) for Notifications when outside a specified interval. I will recommend this for draft-ietf-core-interfaces as well.

Michael Koster noted that a Notification should also be sent when a threshold is crossed and the value would be outside the defined interval(s).

**Comment by ThGarnier** [comment]
A first answer has been addressed by CR08 R01 (2015-02-12) which should clarify this feature; current TS 1.0 reflects this change
