### ISSUE TITLE
LwM2M roadmap, next testfest and future directions

### ISSUE THREAD

**Issue by HAli786** [OpenMobileAlliance/OMA-LwM2M-Public-Review#53]
Hello,

I appreciate if anyone can provide me some information on LwM2M roadmap and next testfest.

1. When is the next testfest scheduled / expected?

2. When the LwM2M version 1.0 specification to be approved (i.e. approved release instead of currently candidate release).

3. What is the next milestone in terms of LwM2M 1.x or 2.x version and their timelines and brief work plan? Is there any document available for public.

Thank you very much

**Comment by jpradocueva** [comment]
Hi there,
Thanks for your questions.
The answers are:

1.When is the next testfest scheduled / expected?
JP: We are planning one towards the end of the Year around ends of November, but plans need to be defined.

2.When the LwM2M version 1.0 specification to be approved (i.e. approved release instead of currently candidate release).
JP: Normally, the recommendation for final approved is based on the outcome of tests results. There are some test cases that still need to gather more evidences before made a final recommendation.


3.What is the next milestone in terms of LwM2M 1.x or 2.x version and their timelines and brief work plan? Is there any document available for public.
JP: So far, there has been some corridor discussions about a new proposal for LwM2M but so far nothing has been officially proposed. Next week there is a meeting where I am expecting to hear more information about a possible new version. You can check back again after a couple of weeks.

**Comment by HAli786** [comment]
Thank you very much, I appreciate that.
