### ISSUE TITLE
TS 8.2.3 Registration Interface : POST or PUT for the 'Update' CoAP Method?

### ISSUE THREAD

**Issue by jaeeunchoi** [OpenMobileAlliance/OMA-LwM2M-Public-Review#96]
About the CoAP Method of 'Update' in the TS section 8.2.3,
the current TS doc (2015 DEC) is written as 'POST' ( "Registration update is performed by sending a CoAP PUT... ").
But the older version of TS ( eg. 2014.NOV) is written as 'PUT'.
And '6.1.2.2 LightweightM2M-1.0-int-102 – Registration Update' in the current test specification ( OMA-ETS-LightweightM2M-V1_0-20151208-C) also uses 'PUT'.

Which one is the correct one? PUT or POST?

**Comment by boaks** [comment]
POST.

See also #85.

**Comment by jpradocueva** [comment]
In the latest TS it is a POST.
Thanks for pointed out the error, it appears that the ETS OMA-ETS-LightweightM2M-V1_0-20151208-C has not been updated accordingly.
I will pass it on to the working group and a change request should be created.

**Comment by jaeeunchoi** [comment]
I see. Currently the 'POST' is the right one.

But I still wonder which method is used by the devices/servers in the real fields now.

Does anyone know how this 'update' test was done in the last TestFest(January,2016) ?
The TestFest result shows that all the participants passed the test case 'LightweightM2M-1.0-int-102 : Registration Update'. They use 'POST' or 'PUT' ?

**Comment by jvermillard** [comment]
[Eclipse Leshan](http://eclipse.org/leshan) hand both PUT and POST registration update for compatibility issues, see code at https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/RegisterResource.java#L304

**Comment by ThGarnier** [comment]
Hello!  the ETS is wrong. In fact the LWM2M TS 1.0 has been changed beginning of 2015 regarding the update registration which was initially mapped on a 'PUT'.
So since that date  (Fev 2015) update registration is mapped on 'POST', the ETS (int 102)  has not been updated yet regarding that point : it will be done ASAP . Great eyes, jaeeunchoi :-)  !!!  many thanks
=> As Julian said there is no issue in leshan, this issue will be turned to "To-be-closed" as soon as the ETS will be fixed on that point

**Comment by jaeeunchoi** [comment]
On the descriptions of 'Registration Update Trigger', 'PUT' should be changed to 'POST', I think.
- Figure25  of 8.2.4 Update Trigger mechanism' in TS doc
- 6.1.2.4 LightweightM2M-1.0-int-104 – Registration Update Trigger
